# Copyright (C) 2020 Sebastian Pipping <sebastian@pipping.org>
# Licensed under GPL v2 or later

name: Run pre-commit

on:
- pull_request
- push

jobs:
  pre-commit:
    name: Run pre-commit
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab  # v3.5.2
    - uses: actions/setup-python@57ded4d7d5e986d7296eab16560982c6dd7c923b  # v4.6.0
      with:
        python-version: 3.11
    - uses: pre-commit/action@646c83fcd040023954eafda54b4db0192ce70507  # v3.0.0
